# Generated by Django 4.2.9 on 2025-12-03 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_initial_data'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_id_83dd09_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_is_acti_847b48_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_deleted_e48316_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_is_admi_63b971_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_created_30b417_idx',
        ),
        migrations.RemoveIndex(
            model_name='usergroup',
            name='user_groups_user_id_084a28_idx',
        ),
        migrations.RemoveIndex(
            model_name='usergroup',
            name='user_groups_group_i_ad7239_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='usergroup',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True, help_text='グループへの所属が有効かどうか', verbose_name='アクティブ'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(db_column='group_name', max_length=100, verbose_name='グループ名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_column='email', max_length=255, null=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True, verbose_name='アクティブ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(db_column='is_admin', default=False, verbose_name='管理者'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(db_column='user_id', max_length=50, primary_key=True, serialize=False, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, db_column='username', max_length=50, null=True, verbose_name='ユーザー名'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='group',
            field=models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, related_name='group_users', to='users.group', verbose_name='グループ'),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
