# Generated by Django 4.2.9 on 2025-10-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_initial_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='論理削除された日時（NULL = 未削除）', null=True, verbose_name='削除日時'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='アカウントが有効かどうか（False = 無効化、ログイン不可）', verbose_name='アクティブ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Django管理サイト（/admin/）にアクセスできるかどうか', verbose_name='スタッフ'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_admin', 'is_active'], name='users_is_admi_63b971_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-created_at'], name='users_created_30b417_idx'),
        ),
    ]
