# Generated by Django 4.2.9 on 2025-10-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_initial_superuser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='削除日時'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['deleted_at', 'is_active'], name='custom_user_deleted_0fc1e4_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['deleted_at', 'is_admin'], name='custom_user_deleted_4e32a9_idx'),
        ),
    ]
