# Generated by Django 4.2.9 on 2025-10-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_deleted_at_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(db_index=True, help_text='ログイン認証に使用する一意の社員番号（論理削除時も番号をそのまま保持）', max_length=50, unique=True, verbose_name='社員番号'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('employee_id',), name='unique_active_employee_id'),
        ),
    ]
