# Generated by Django 4.2.9 on 2025-10-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(db_index=True, help_text='ログイン認証に使用する一意の社員番号（論理削除時も番号をそのまま保持）', max_length=50, verbose_name='社員番号'),
        ),
    ]
