# Generated by Django 4.2.9 on 2025-11-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_deleted_at_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['deleted_at', 'is_admin', 'is_active'], name='users_admin_count_idx'),
        ),
    ]
