# Generated by Django 4.2.9 on 2025-10-09 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, help_text='X-Request-ID または自動生成されたUUID', max_length=36, verbose_name='リクエストID')),
                ('employee_id', models.CharField(blank=True, help_text='削除されたユーザーのために保存', max_length=20, null=True, verbose_name='社員番号')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='ユーザー名')),
                ('action', models.CharField(choices=[('CREATE', '作成'), ('UPDATE', '更新'), ('DELETE', '削除'), ('LOGIN', 'ログイン'), ('LOGOUT', 'ログアウト'), ('LOGIN_FAILED', 'ログイン失敗'), ('VIEW', '閲覧'), ('RESTORE', '復元'), ('BULK_DELETE', '一括削除'), ('BULK_RESTORE', '一括復元')], db_index=True, max_length=20, verbose_name='アクション')),
                ('model_name', models.CharField(db_index=True, help_text='User, Product など', max_length=50, verbose_name='モデル名')),
                ('object_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='オブジェクトID')),
                ('changes', models.JSONField(blank=True, help_text='変更前後の値を記録', null=True, verbose_name='変更内容')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IPアドレス')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('endpoint', models.CharField(blank=True, help_text='/api/users/1/ など', max_length=255, null=True, verbose_name='エンドポイント')),
                ('method', models.CharField(blank=True, help_text='GET, POST, PUT, DELETE など', max_length=10, null=True, verbose_name='HTTPメソッド')),
                ('success', models.BooleanField(default=True, verbose_name='成功')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='エラーメッセージ')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='実行日時')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='実行ユーザー')),
            ],
            options={
                'verbose_name': '監査ログ',
                'verbose_name_plural': '監査ログ',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['request_id'], name='audit_logs_request_298ea7_idx'), models.Index(fields=['user', 'timestamp'], name='audit_logs_user_id_88267f_idx'), models.Index(fields=['action', 'timestamp'], name='audit_logs_action_474804_idx'), models.Index(fields=['model_name', 'object_id'], name='audit_logs_model_n_656046_idx')],
            },
        ),
    ]
